platform :osx, '10.12'

use_frameworks!


target 'Sample_macOS' do

	pod 'Dopamine', :path => '../..'

end

post_install do |installer|
	installer.pods_project.targets.each do |target|
		if target.name == "Dopamine"
			target.build_configurations.each do |config|
				if config.name.match(/^Debug/)
					config.build_settings['OTHER_SWIFT_FLAGS'] ='$(inherited) -D DEBUG'
					else
					config.build_settings['OTHER_SWIFT_FLAGS'] ='$(inherited)'
				end
			end
		end
	end
	
	installer.pods_project.build_configurations.each do |config|
		if config.name.match(/^Debug/)
			config.build_settings['GCC_OPTIMIZATION_LEVEL'] = '0'
		end
	end
end
